name: CI - Saucedemo

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.1

    - name: Set up JDK 11
      uses: actions/setup-java@v2.7.0 
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B
